# permissions for end users to view rabbits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbit-viewer-role
rules:
- apiGroups:
  - farm.rabbitco.io
  resources:
  - rabbits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - farm.rabbitco.io
  resources:
  - rabbits/status
  verbs:
  - get
